INSERT INTO alunos (nome) VALUES
('Arthur Bezerra'),
('Beatriz Fontes'),
('Bruno Santos'),
('Camila Farias '),
('Camila Lins'),
('Carlos Silva'),
('Clodoaldo Santos'),
('Eduardo Coitinho '),
('Elton Santos'),
('Eridiana Nascimento'),
('Estevão Lucas'),
('Ismael Silva'),
('Ítalo Silva'),
('Joelma Sena '),
('Leandro Filho'),
('Luciana De Araújo'),
('Marcos Barros'),
('Maria Silva'),
('Meydson Baracho'),
('Paulo Filho'),
('Rackel Ramos'),
('Robert França '),
('Ryan Menezes'),
('Tarcisio Filho'),
('Thayná Parahyba'),
('Thiago Vilela'),
('Vinicius Lima'),
('Vitória Lira'),
('Wagner Vidal'),
('Yuri Pereira');
