INSERT INTO alunos (nome) VALUES
('Arthur Vinícius Bezerra Da Silva'),
('Beatriz Gonçalves Fontes'),
('Bruno Cesar Soares Dos Santos'),
('Camila Pâmela Bacelar Barbosa Farias '),
('Camila Siqueira Lins'),
('Carlos Eduardo Da Silva'),
('Clodoaldo Braga Batista Dos Santos'),
('Eduardo Henrique Guerra Coitinho '),
('Elton Emanuel Soares Santos'),
('Eridiana Angelica Dias Do Nascimento'),
('Estevão Lucas Ramos Da Silva'),
('Ismael Silva'),
('Ítalo Silva'),
('Joelma Ceciliana De Sena '),
('Leandro José Da Silva Filho'),
('Luciana Carla Alves Costa De Araújo'),
('Marcos André Monteiro De Barros'),
('Maria Letícia Da Silva Manguinho'),
('Meydson Lenyerge Lima Baracho'),
('Paulo Carlos Da Silva Filho'),
('Rackel Ramos'),
('Robert França '),
('Ryan Silva De Menezes'),
('Tarcisio Varjão Gomes Da Silva Filho'),
('Thayná Ribeiro Parahyba'),
('Thiago Vilela'),
('Vinicius Ferreira De Lima'),
('Vitória Carla Costa De Lira'),
('Wagner Vidal Xavier Da Silva'),
('Yuri Pereira');