CREATE DATABASE dbAcademicNotes;
CREATE DATABASE IF NOT EXISTS dbAcademicNotes;

use dbAcademicNotes; 

CREATE TABLE IF NOT EXISTS STUDENTS 
(
	STUDENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STUDENT_NAME varchar(50),
    STUDENT_STATUS BOOL    
);

CREATE TABLE IF NOT EXISTS NOTES (
    NOTE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOTE_VALUE DOUBLE,
    STUDENT_ID INT,
    CONSTRAINT FK_STUDENTS FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENTS (STUDENT_ID)
);
