/* Insert Into - Student */

INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Arthur Vinícius Bezerra Da Silva');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Beatriz Gonçalves Fontes');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Bruno Cesar Soares Dos Santos');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Camila Pâmela Bacelar Barbosa Farias');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Camila Siqueira Lins');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Carlos Eduardo Da Silva');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Clésio Salles');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Clodoaldo Braga Batista Dos Santos');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Ednilson Vicente Calixto');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Eduardo Henrique Guerra Coitinho');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Elton Emanuel Soares Santos');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Eridiana Angelica Dias Do Nascimento');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Estevão Lucas Ramos Da Silva');
INSERT INTO 'jacademic`.`student` (`name_student`) VALUES ('Everton Pedrosa');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Ismael Silva');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Ítalo Silva');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Janderson Araujo');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Joelma Ceciliana De Sena');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Jose Junior');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Larissa Silva');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Leandro José Da Silva Filho');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Luciana Carla Alves Costa De Araújo');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Marcos André Monteiro De Barros');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Maria Letícia Da Silva Manguinho');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Matheus Bezerra');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Matheus Trajano Costa');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Meydson Lenyerge Lima Baracho');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Paulo Carlos Da Silva Filho');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Pedro Moura');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Rackel Ramos');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Reyvson Albuquerque');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Robert França');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Ryan Silva De Menezes');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Tarcisio Varjão Gomes Da Silva Filho');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Thayná Ribeiro Parahyba');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Thiago Vilela');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Vanik Lima');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Vinicius Ferreira De Lima');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Vitória Carla Costa De Lira');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Wagner Vidal Xavier Da Silva');
INSERT INTO 'jacademic'.'student' ('name_student') VALUES ('Yuri Pereira');

/* Insert Into - Note*/

INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('1');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('2');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('3');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('4');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('5');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('6');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('7');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('8');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('9');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('10');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('11');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('12');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('13');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('14');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('15');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('16');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('17');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('18');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('19');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('20');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('21');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('22');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('23');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('24');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('25');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('26');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('27');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('28');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('29');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('30');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('31');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('32');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('33');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('34');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('35');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('36');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('37');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('38');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('39');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('40');
INSERT INTO `jacademic`.`note` (`id_student`) VALUES ('41');
